### ISSUE TITLE
Blogs : Code should be text and not an image

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/Algorithmist#2]
**https://algorithmist-dev.web.app/blogs/all-shortest-path-algorithms** check this page out. You can see a couple of codes written on black background, which are images. 
Some people might want to copy the code so I want the code to be written in text, like in other coding websites.

**Comment by M1racle04** [comment]
Hey, What you can do is instead of adding an image of the code, write it normally in the doc fie and the put it in a table, and make the background black and the text white. This will make the code look like an image, but people can copy it. 
I am linking one article of mine for reference: https://docs.google.com/document/d/1CIFObniS5aMKvgTw78FiigOG4umOKeF1AyaSX8yYUUc/edit?usp=sharing

**Comment by Nayaker** [comment]
It's a really great info, thanks

**Comment by Nayaker** [comment]
I iframed google docs
