### ISSUE TITLE
Implement Local Storage on Question Completed 

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/Algorithmist#54]
If you check the https://algorithmist-dev.web.app/coding-sheets page you can see a lot of questions of a particular sheet coming from the backend. 

If you click the tick button on the right side of each question, it is marked as completed and the color changes. 

<img width="1042" alt="Screenshot 2022-12-26 at 11 22 20 AM" src="https://user-images.githubusercontent.com/93304796/209508622-77350e69-0967-4dcb-956d-aa92563974f1.png">

However, since the data from the backend has all the questions marked completed as false, hence when we refresh the page color of previously marked questions become the same as before. 

I want to implement local storage for the questions completed, i.e., store the questions which are completed in the user's local storage so that it stays after refresh and also after reopening the site.

**Comment by JordanAdair** [comment]
This is happening because the solution I provided only interacts with the dummy data. I don't believe saving to local storage is necessary. If you'd like the changes to be permanent, you'll need to load and manipulate the data in the database. If you'd like, I'd be happy to take on this task. Just let me know and I'll get started.

**Comment by JordanAdair** [comment]
Hi,  I'd be happy to take on this task. Just let me know and I'll get started.

**Comment by Nayaker** [comment]
Yeah, great @JordanAdair you can start working on it. I have assigned the task to you  :)

**Comment by JordanAdair** [comment]
@Nayaker I also see you need content writers. I'd love to write about UI/UX principles! Figure it would be a great learning opportunity. Let me know what you think.

**Comment by Nayaker** [comment]
Sure @JordanAdair, I'd love to have you as a blog writer and let you choose your own topics. If you're interested in joining our WhatsApp group where we discuss important information about the blogs, please send me your phone number and email to give you access to the Google Sheets documents.

<img width="1004" alt="Screenshot 2022-12-27 at 3 08 26 AM" src="https://user-images.githubusercontent.com/93304796/209584657-f6e80946-fb6f-4abd-8853-9e2eaca20b82.png">

<img width="761" alt="Screenshot 2022-12-27 at 3 10 05 AM" src="https://user-images.githubusercontent.com/93304796/209584736-eb939bf4-af7c-4b99-a907-c938f41ec0e5.png">

**Comment by JordanAdair** [comment]
Do you guys have a Discord or something? I don't really feel super comfortable giving out such sensitive information on here. 😅

**Comment by Nayaker** [comment]
Actually no we don't. Ok, no issues I am sure we can manage so another way for this. I will let you know, soon :)

**Comment by JordanAdair** [comment]
I appreciate it! I look forward to contributing.

**Comment by JordanAdair** [comment]
@Nayaker I'm having a lot of difficulty working around the way that we currently load each set of sheets. 
As far as I understand it, we're resetting the Data variable and CompletedCount on first load, as well as every time a filter button is pressed: 

```
	useEffect(() => {
		setData([]); <--- HERE
		axios
			.get(`https://algolisted.cyclic.app/coding-sheets/sheet/${filterDomain}`)
			.then((res) => {
				setData(res.data);
				console.log("searching for ", filterDomain);
				console.log("All data : ", res.data);
			})
			.catch((err) => console.log(err));
		setCompletedCount(0); <-- AND HERE
	}, [filter]);
```

From what I can tell, this is preventing me from saving local data, as it's overwriting these values every time the page is loaded or a filter is clicked. 

My proposed solution is to load the list in it's entirety a single time on page launch, and then use the filters to show or hide specific results. Aesthetically this would function the exact same, but this would allow me to maintain local data because there is no data loss under the hood. This would also significantly reduce the amount of calls to the database, however initial load times would be slower than they currently are, and as this project scales that may end up being problematic. 

If you're interested in this approach, I'll need to know what end-point to reference instead of `.get('https://algolisted.cyclic.app/coding-sheets/sheet/${filterDomain}')` to get every sheet at once. 

Or, if you're interested in a using different approach, please let me know. This is my first time using local storage, so I could always be totally misunderstanding something here.

**Comment by Nayaker** [comment]
Hi @JordanAdair, I hope you're doing well! I am having some trouble with the mobile responsive design of my website and I'm stuck on an issue (https://github.com/Nayaker/AlgoListed/issues/61) that I need to resolve before the website launch. Mobile responsive design isn't my strongest area, so I was wondering if you might be able to lend a hand and help me resolve this issue.

**Comment by JordanAdair** [comment]
No worries, I'll check it out.
